name: Frontend Integration Tests

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        default: '18'
        type: string
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js ${{ inputs.node-version || '18' }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version || '18' }}
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
      
    - name: Run integration tests
      run: |
        cd frontend
        npm run test:integration
      env:
        CI: true
